# Generated by Django 4.2.23 on 2025-10-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('dispatched', 'Dispatched'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
