"""Add stock_adjusted boolean to Order to make stock adjustments idempotent.

Generated by assistant.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stock_adjusted",
            field=models.BooleanField(default=False),
        ),
    ]
