# Generated by Django 4.2.23 on 2025-10-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kettlebell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(choices=[(8, '8 kg'), (12, '12 kg'), (16, '16 kg'), (20, '20 kg'), (24, '24 kg'), (28, '28 kg'), (32, '32 kg'), (36, '36 kg'), (40, '40 kg'), (48, '48 kg')], unique=True)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
