# Generated by Django 4.2.23 on 2025-10-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kettlebell_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kettlebell',
            name='price_gbp',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in GBP', max_digits=3),
        ),
    ]
