# Generated by Django 4.2.23 on 2025-10-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kettlebell_shop', '0003_alter_kettlebell_price_gbp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kettlebell',
            name='weight',
            field=models.PositiveIntegerField(choices=[(8, '8 kg '), (12, '12 kg'), (16, '16 kg'), (20, '20 kg'), (24, '24 kg'), (28, '28 kg'), (32, '32 kg'), (36, '36 kg'), (40, '40 kg'), (48, '48 kg')], unique=True),
        ),
    ]
