# Generated by Django 4.2.23 on 2025-10-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kettlebell_shop', '0004_alter_kettlebell_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='kettlebell',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kettlebells/'),
        ),
        migrations.AddField(
            model_name='kettlebell',
            name='preset_weight',
            field=models.CharField(blank=True, choices=[('8', '8 kg'), ('12', '12 kg'), ('16', '16 kg'), ('20', '20 kg'), ('24', '24 kg'), ('28', '28 kg'), ('32', '32 kg'), ('36', '36 kg'), ('40', '40 kg'), ('48', '48 kg')], help_text='Pick a preset kg weight or leave blank for a custom weight', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kettlebell',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], default='kg', max_length=2),
        ),
        migrations.AlterField(
            model_name='kettlebell',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterUniqueTogether(
            name='kettlebell',
            unique_together={('weight', 'weight_unit')},
        ),
    ]
