# Generated by Django 4.2.23 on 2025-10-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kettlebell_shop', '0005_kettlebell_image_kettlebell_preset_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kettlebell',
            name='image',
        ),
    ]
